import type { Metadata } from "next";
import { inter, poppins, outfit, dmSans } from "@/fonts";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${poppins.variable} ${outfit.variable} ${dmSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
